### ISSUE TITLE
Update compilers from 7.3 to 7.5

### ISSUE THREAD

**Issue by mike-wendt** [rapidsai/ucx-split-feedstock#33]
@jakirkham with the updates across RAPIDS to 7.5 and the conda-forge updates, can we update these configs as well?

**Comment by jakirkham** [comment]
Fine by me. Would it be ok if we drop the compiler constrain altogether?

**Comment by mike-wendt** [comment]
> Fine by me. Would it be ok if we drop the compiler constraint altogether?

If that's how it was before and we'd still be able to work with it RAPIDS on 7.5 then that works.

**Comment by jakirkham** [comment]
Yep both those things are true. Cool will send a PR. Thanks Mike 😄

**Comment by jakirkham** [comment]
Sorry for the delay here. Submitted PR ( https://github.com/rapidsai/ucx-split-feedstock/pull/35 ), which relaxes the compiler pinning. Please take a look 🙂
