### ISSUE TITLE
Switch to use hashes in conda pkg names like the rest of RAPIDS

### ISSUE THREAD

**Issue by mike-wendt** [rapidsai/ucx-split-feedstock#38]
Similar to other libraries use the current git hash in conda package build strings to allow for benchmarking and troubleshooting.

**Comment by jakirkham** [comment]
Partially addressed in PR ( https://github.com/rapidsai/ucx-split-feedstock/pull/45 )

**Comment by jakirkham** [comment]
Remaining part of the fix is in PR ( https://github.com/rapidsai/ucx-split-feedstock/pull/73 ), but may need more work.

**Comment by jakirkham** [comment]
`ucx` builds are now coming from `conda-forge`. So they follow that build process.

`ucx-py` builds are handled in [the `ucx-py` repo's recipe]( https://github.com/rapidsai/ucx-py/tree/branch-0.26/conda/recipes/ucx-py ). Those have been constructed to follow other RAPIDS package builds (likely resolving this issue). Though if any other fixes are needed, they can be handled there.
