### ISSUE TITLE
Build Conda package for 1.12.1

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-split-feedstock#80]
[UCX 1.12.1](https://github.com/openucx/ucx/releases/tag/v1.12.1) was release at the end of March

**Comment by jakirkham** [comment]
FWIW this was updated recently in conda-forge ( https://github.com/conda-forge/ucx-split-feedstock/pull/92 ).

**Comment by quasiben** [comment]
Rather than rely on rapidsai for build UCX, @jakirkham proposed in a call we rely on the conda-forge build.  I think this is something we should consider.  Some things to do before adopting and questions to ask:

- validate conda-forge ucx builds are complaint and performs similarly to the rapidsai build
- Can the conda-forge package be build with the latest rdma-core package (@pentschev can you supply the version number) ?
- Is UCX core generally stable enough for us to only depend on releases rather than the patches we have relied on in the past?

**Comment by pentschev** [comment]
We would require rdma-core >= 28.0. AFAIK, it's not available for CentOS 7, so I'm not sure if/how that can be supported.

**Comment by jakirkham** [comment]
Now using conda-forge packages for which this version has already been produced. Going to close this out as resolved
